[package]
name = "vcflib"
version = "0.1.0"
authors = ["Savvas Savvides <savvas@purdue.edu>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
flate2 = "1.0"
linked-hash-map = "0.5"

[package.metadata.fortanix-sgx]
stack-size=0x200000
heap-size=0x20000000
threads=1
ssaframesize=1
debug=true